Repository OpenMined/PyGridNetwork, pull requests merged in 2020-06, with the labels that each got.

#16 Conform README to org's template
  README.md
Labels: Type: Documentation :books:

#22 Import routes and events on the gridnetwork module
  gridnetwork/__init__.py
Labels: Priority: 2 - High :cold_sweat:, Type: Bug :bug:

#20 Move network routing [PyGrid -> GridNetwork]
  gridnetwork/__init__.py
  gridnetwork/network/__init__.py
  gridnetwork/network/network_manager.py
  gridnetwork/network/nodes.py
  gridnetwork/routes/__init__.py
  gridnetwork/routes/network.py
  gridnetwork/routes/nodes.py
  requirements.txt
  run.py
  setup.py
Labels: Status: In Progress :star2:

#27 ADD support section
  README.md
Labels: Priority: 3 - Medium :unamused:, Severity: 4 - Low :sunglasses:

#30 Automated Docker builds
  .github/workflows/docker-build.yml
Labels: Type: New Feature :heavy_plus_sign:

#31 Setup Github Actions workflow for unit testing
  .github/workflows/tests.yml
  gridnetwork/routes/network.py
  test/conftest.py
  test/test_network.py
Labels: Type: New Feature :heavy_plus_sign:, Type: Testing :test_tube:

#32 Add CI status badge to README
  README.md
Labels: Type: Documentation :books:

#34 Fix/workers documentation
  .gitignore
  gridnetwork/events/socket_handler.py
  gridnetwork/workers/worker.py
Labels: Type: Documentation :books:

#39 Make utils first local module imported
  gridnetwork/__init__.py
  gridnetwork/utils/__init__.py
Labels: Type: Bug :bug:

#37 Fix/routes documentation
  gridnetwork/network/network_manager.py
  gridnetwork/routes/dataset.py
  gridnetwork/routes/general.py
  gridnetwork/routes/models.py
  gridnetwork/routes/network.py
  gridnetwork/routes/nodes.py
Labels: Type: Documentation :books:

#40 Rename package to conform to org scoping
  .gitignore
  README.md
  setup.py
Labels: Type: Improvement :chart_with_upwards_trend:
